# Generated by Django 6.0.4 on 2026-05-10 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('matricule', models.CharField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fonctions', models.CharField(choices=[('Etudiant', 'Etudiant'), ('Formateur', 'Formateur'), ('Employé', 'Employé')])),
            ],
        ),
        migrations.CreateModel(
            name='CompteAdherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Refusée', 'Refusée')], default='En attente')),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent')),
                ('valider_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('livre', models.ForeignKey(limit_choices_to={'quantite__gt': 0}, on_delete=django.db.models.deletion.CASCADE, to='livres.livre')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligneReservation', to='adherents.reservation')),
            ],
        ),
    ]
