# Generated by Django 6.0.4 on 2026-05-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0004_reservation_detailreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailreservation',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligneReservation', to='adherents.reservation'),
        ),
    ]
