# Generated by Django 6.0.4 on 2026-05-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0005_alter_detailreservation_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_commande',
            new_name='date_reservation',
        ),
    ]
