# Generated by Django 6.0.4 on 2026-05-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.adherent')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
