# Generated by Django 6.0.4 on 2026-05-09 07:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adherents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_limite', models.DateField(default=datetime.datetime(2026, 5, 24, 9, 26, 7, 27398))),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En retard', 'En retard'), ('Retourné', 'Retourné'), ('Non retourné', 'Non retourné')], default='Non retourné')),
                ('remarque', models.TextField(blank=True, default=' ')),
                ('bibliothecaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.reservation')),
            ],
        ),
    ]
