# Generated by Django 6.0.4 on 2026-05-10 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0002_alter_emprunt_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 25, 15, 29, 1, 819319)),
        ),
    ]
