# Generated by Django 6.0.4 on 2026-05-12 14:24

import emprunts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0003_alter_emprunt_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=emprunts.models.date_limite_par_defaut),
        ),
    ]
