# Generated by Django 6.0.4 on 2026-05-05 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0007_alter_emprunt_date_limite_alter_emprunt_remarque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 20, 16, 32, 47, 726173)),
        ),
    ]
