# Generated by Django 6.0.4 on 2026-05-06 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0008_alter_emprunt_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 21, 4, 36, 23, 97043)),
        ),
    ]
