# Generated by Django 6.0.4 on 2026-05-06 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0009_alter_emprunt_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 21, 8, 42, 52, 764215)),
        ),
    ]
