# Generated by Django 6.0.4 on 2026-05-06 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0011_alter_emprunt_date_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='ref_livre',
            new_name='reservation',
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='adherent',
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 21, 11, 24, 25, 240002)),
        ),
    ]
