# Generated by Django 6.0.4 on 2026-05-06 11:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adherents', '0006_rename_date_commande_reservation_date_reservation'),
        ('emprunts', '0012_rename_ref_livre_emprunt_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprunt',
            name='date_limite',
            field=models.DateField(default=datetime.datetime(2026, 5, 21, 11, 31, 35, 882385)),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adherents.reservation'),
        ),
    ]
