# Generated by Django 6.0.4 on 2026-05-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprunts', '0002_alter_emprunt_date_limite'),
        ('emprunts', '0013_alter_emprunt_date_limite_alter_emprunt_reservation'),
    ]

    operations = [
    ]
